# Reference: https://golangci-lint.run/usage/configuration/#config-file

skip-dirs:
  - src
timeout: 5m
linters-settings:
  goimports:
    local-prefixes: github.com/timzatko/fiit-pdt

linters:
  enable:
    - goimports