# https://hub.docker.com/_/postgres

version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080