# https://hub.docker.com/_/postgres

version: '3.1'

volumes:
  postgis-data:

services:

  postgres:
    # https://github.com/postgis/docker-postgis
    image: postgis/postgis
    restart: always
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "${PDT_DATABASE_DB}"
      POSTGRES_USER: "${PDT_DATABASE_USER}"
      POSTGRES_PASSWORD: "${PDT_DATABASE_PASSWORD}"
    ports:
      - "5432:5432" # expose postgresql ports to local machine and other services
    command: "-c log_statement=none" # "-c log_statement=all" # use this for debugging

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080