# https://hub.docker.com/_/postgres

version: '3.1'

volumes:
  postgis-data:

services:

  postgres:
    image: postgis/postgis
    restart: always
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tweets
    ports:
      - "5432:5432" # expose postgresql ports to local machine and other services

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080